name: build

on:
  push:
    paths:
      - ".github/**"
      - "CMakeLists.txt"
      - "src/**"

permissions:
  contents: write

env:
  ARCH: Win32
  GENERATOR: Visual Studio 17 2022
  CONFIG: Release
  FILENAME: dinput8.dll
  BUILD_DIR: build

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - name: Configure project
        run: cmake . -B $env:BUILD_DIR -G $env:GENERATOR -A $env:ARCH

      - name: Build project
        run: cmake --build $env:BUILD_DIR --config $env:CONFIG

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./${{env.BUILD_DIR}}/${{env.CONFIG}}/${{env.FILENAME}}
